INSERT OR REPLACE INTO IconDefinitions (Name, Atlas, 'Index') VALUES
('ICON_POLICY_SIEGE', 'ICON_ATLAS_POLICIES', '1'),
('ICON_POLICY_HARD_SHELL_EXPLOSIVES', 'ICON_ATLAS_POLICIES', '1'),
('ICON_POLICY_TRENCH_WARFARE', 'ICON_ATLAS_POLICIES', '1'),
('ICON_VICTORY_TRADITIONAL_DOMINATION', 'ICON_ATLAS_VICTORIES', '3');

