------------------------------------------------------------------------------
--	FILE:	 config.sql
--	AUTHOR:  iElden, D. / Jack The Narrator
--	PURPOSE: Config Database adjustment for front-end
------------------------------------------------------------------------------
--==============================================================================================
--******								ADDITIONAL CONFIG								******
--==============================================================================================

-- “无蛮族”选项不可见
UPDATE Parameters SET Visible=0 WHERE Key2 IN ('RULESET_STANDARD', 'RULESET_EXPANSION_1', 'RULESET_EXPANSION_2') AND ConfigurationId='GAME_NO_BARBARIANS';

INSERT OR REPLACE INTO Victories (Domain, VictoryType, Name, Description, Visible) VALUES
('Expansion2_Victories', 'VICTORY_TRADITIONAL_DOMINATION', 'LOC_VICTORY_TRADITIONAL_DOMINATION_NAME', 'LOC_VICTORY_TRADITIONAL_DOMINATION_TT', '1'),
('Expansion2_Victories', 'VICTORY_CONQUEST', 'LOC_VICTORY_DOMINATION_NAME', 'LOC_VICTORY_DOMINATION_TT', '1'),
('Expansion2_Victories', 'VICTORY_CULTURE', 'LOC_VICTORY_CULTURE_NAME', 'LOC_VICTORY_CULTURE_TT', '1'),
('Expansion2_Victories', 'VICTORY_RELIGIOUS', 'LOC_VICTORY_RELIGIOUS_NAME', 'LOC_VICTORY_RELIGIOUS_TT', '1'),
('Expansion2_Victories', 'VICTORY_SCORE', 'LOC_VICTORY_SCORE_NAME', 'LOC_VICTORY_SCORE_TT', '1'),
('Expansion2_Victories', 'VICTORY_TECHNOLOGY', 'LOC_VICTORY_SCIENCE_NAME', 'LOC_VICTORY_SCIENCE_TT_XP2', '1'),
('Expansion2_Victories', 'VICTORY_DIPLOMATIC', 'LOC_VICTORY_DIPLOMATIC_NAME', 'LOC_VICTORY_DIPLOMATIC_TT', '1');

INSERT OR REPLACE INTO Parameters (ParameterId, Name, Description, Domain, DefaultValue, ConfigurationGroup, ConfigurationId, GroupId, SupportsSinglePlayer, SupportsPlayByCloud, SupportsHotSeat, SortIndex, Visible, Hash) VALUES
('BBCC_SETTING', 'BBCC_SETTING_NAME', 'BBCC_SETTING_DESC', 'BBCCSetting', '-1', 'Game', 'BBCC_SETTING', 'GameOptions', '1', '1', '1', '10', DEFAULT, DEFAULT),
('BBCC_SETTING_YIELD', 'BBCC_SETTING_YIELD_NAME', 'BBCC_SETTING_YIELD_DESC', 'BBCCSettingYield', '0', 'Game', 'BBCC_SETTING_YIELD', 'GameOptions', '1', '1', '1', '11', DEFAULT, DEFAULT),
('SettlersConfig', 'LOC_BBG_SETTLER_CONFIG_NAME', 'BBG_SETTLER_CONFIG_DESC', 'SettlersConfig', '-1', 'Game', 'SettlersConfig', 'GameOptions', '1', '1', '1', '12', DEFAULT, DEFAULT),
('TRADITIONAL_DOMINATION_LEVEL', 'Domination Level', 'Description', 'int', '66', 'Game', 'TRADITIONAL_DOMINATION_LEVEL', 'AdvancedOptions', DEFAULT, DEFAULT, DEFAULT, DEFAULT, '0', DEFAULT),
('VICTORY_TRADITIONAL_DOMINATION', 'LOC_VICTORY_TRADITIONAL_DOMINATION_NAME', 'LOC_VICTORY_TRADITIONAL_DOMINATION_TT', 'bool', '1', 'Game', 'VICTORY_TRADITIONAL_DOMINATION', 'Victories', DEFAULT, DEFAULT, DEFAULT, DEFAULT, '1', DEFAULT),
('VICTORY_CONQUEST', 'LOC_VICTORY_DOMINATION_NAME', 'LOC_VICTORY_DOMINATION_TT', 'bool', '1', 'Game', 'VICTORY_CONQUEST', 'Victories', DEFAULT, DEFAULT, DEFAULT, DEFAULT, '1', DEFAULT),
('VICTORY_CULTURE', 'LOC_VICTORY_CULTURE_NAME', 'LOC_VICTORY_CULTURE_TT', 'bool', '1', 'Game', 'VICTORY_CULTURE', 'Victories', DEFAULT, DEFAULT, DEFAULT, DEFAULT, '1', DEFAULT),
('VICTORY_RELIGIOUS', 'LOC_VICTORY_RELIGIOUS_NAME', 'LOC_VICTORY_RELIGIOUS_TT', 'bool', '1', 'Game', 'VICTORY_RELIGIOUS', 'Victories', DEFAULT, DEFAULT, DEFAULT, DEFAULT, '1', DEFAULT),
('VICTORY_SCORE', 'LOC_VICTORY_SCORE_NAME', 'LOC_VICTORY_SCORE_TT', 'bool', '1', 'Game', 'VICTORY_SCORE', 'Victories', DEFAULT, DEFAULT, DEFAULT, DEFAULT, '1', DEFAULT),
('VICTORY_TECHNOLOGY', 'LOC_VICTORY_SCIENCE_NAME', 'LOC_VICTORY_SCIENCE_TT_XP2', 'bool', '1', 'Game', 'VICTORY_TECHNOLOGY', 'Victories', DEFAULT, DEFAULT, DEFAULT, DEFAULT, '1', DEFAULT),
('VICTORY_DIPLOMATIC', 'LOC_VICTORY_DIPLOMATIC_NAME', 'LOC_VICTORY_DIPLOMATIC_TT', 'bool', '1', 'Game', 'VICTORY_DIPLOMATIC', 'Victories', DEFAULT, DEFAULT, DEFAULT, DEFAULT, '1', DEFAULT),
('VictoryMasterSlider', 'BBG_FRONT_VICTORY_SPEED_SLIDER_NAME', 'BBG_FRONT_VICTORY_SPEED_SLIDER_DESC', 'BBGVictorySpeedSliderRange', '5', 'Game', 'BBGVictorySpeedSlider', 'Victories', DEFAULT, DEFAULT, DEFAULT, '0', DEFAULT, '0'),
('VictoryCulturalSetting', 'LOC_VICTORY_CULTURE_NAME', 'BBG_FRONT_VICTORY_CULTURAL_SETTING_DESC', 'BBGVictoryCulturalSettingDomain', '0', 'Game', 'VictoryCulturalSetting', 'Victories', DEFAULT, DEFAULT, DEFAULT, '1', DEFAULT, DEFAULT),
('VictoryScoreSetting', 'LOC_VICTORY_SCORE_NAME', 'BBG_FRONT_VICTORY_SCORE_SETTING_DESC', 'BBGVictoryScoreSettingDomain', '0', 'Game', 'VictoryScoreSetting', 'Victories', DEFAULT, DEFAULT, DEFAULT, '7', DEFAULT, DEFAULT),
('VictoryScienceSetting', 'LOC_VICTORY_SCIENCE_NAME', 'BBG_FRONT_VICTORY_SCIENCE_SETTING_DESC', 'BBGVictoryScienceSettingDomain', '0', 'Game', 'VictoryScienceSetting', 'Victories', DEFAULT, DEFAULT, DEFAULT, '3', DEFAULT, DEFAULT),
('VictoryDiploSetting', 'LOC_VICTORY_DIPLOMATIC_NAME', 'BBG_FRONT_VICTORY_DIPLO_SETTING_DESC', 'BBGVictoryDiploSettingDomain', '0', 'Game', 'VictoryDiploSetting', 'Victories', DEFAULT, DEFAULT, DEFAULT, '4', DEFAULT, DEFAULT),
('VictoryDominationSetting', 'LOC_VICTORY_TRADITIONAL_DOMINATION_NAME', 'BBG_FRONT_VICTORY_DOMINATION_SETTING_DESC', 'BBGVictoryDominationSettingDomain', '0', 'Game', 'VictoryDominationSetting', 'Victories', DEFAULT, DEFAULT, DEFAULT, '5', DEFAULT, DEFAULT),
('VictoryConquestSetting', 'LOC_VICTORY_CONQUEST_NAME', 'BBG_FRONT_VICTORY_CONQUEST_SETTING_DESC', 'BBGVictoryConquestSettingDomain', '0', 'Game', 'VictoryConquestSetting', 'Victories', DEFAULT, DEFAULT, DEFAULT, '5', DEFAULT, DEFAULT),
('VictoryReligiousSetting', 'LOC_VICTORY_RELIGIOUS_NAME', 'BBG_FRONT_VICTORY_RELIGIOUS_SETTING_DESC', 'BBGVictoryReligiousSettingDomain', '0', 'Game', 'VictoryReligiousSetting', 'Victories', DEFAULT, DEFAULT, DEFAULT, '6', DEFAULT, DEFAULT),
('BarbariansSetting', 'BBG_FRONT_BARBARIANS_SETTING_NAME', 'BBG_FRONT_BARBARIANS_SETTING_DESC', 'BBGBarbsSetting', '1', 'Game', 'BARBS_SETTING', 'AdvancedOptions', DEFAULT, DEFAULT, DEFAULT, '2010', DEFAULT, DEFAULT);

INSERT OR REPLACE INTO ParameterCriteria (ParameterId, ConfigurationGroup, ConfigurationId, Operator, ConfigurationValue) VALUES
('BBCC_SETTING_YIELD', 'Game', 'BBCC_SETTING', 'NotEquals', '-1'),
('VICTORY_CULTURE', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '-1'),
('VICTORY_CONQUEST', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '-1'),
('VICTORY_RELIGIOUS', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '-1'),
('VICTORY_SCORE', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '-1'),
('VICTORY_TECHNOLOGY', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '-1'),
('VICTORY_DIPLOMATIC', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '-1'),
('VICTORY_TRADITIONAL_DOMINATION', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '-1'),
('TurnLimit', 'Game', 'BBGVictoryScoreSettingDomain', 'NotEquals', '3'),
('MaxTurns', 'Game', 'BBGVictoryScoreSettingDomain', 'NotEquals', '0'),
('MaxTurns', 'Game', 'BBGVictoryScoreSettingDomain', 'NotEquals', '1'),
('MaxTurns', 'Game', 'BBGVictoryScoreSettingDomain', 'NotEquals', '2'),
('MaxTurns', 'Game', 'BBGVictoryScoreSettingDomain', 'NotEquals', '3');

INSERT OR REPLACE INTO ParameterDependencies (ParameterId, ConfigurationGroup, ConfigurationId, Operator, ConfigurationValue) VALUES
('VictoryCulturalSetting', 'Game', 'BBGVictorySpeedSlider', 'Equals', '3'),
('VictoryScoreSetting', 'Game', 'BBGVictorySpeedSlider', 'Equals', '3'),
('VictoryScienceSetting', 'Game', 'BBGVictorySpeedSlider', 'Equals', '3'),
('VictoryDiploSetting', 'Game', 'BBGVictorySpeedSlider', 'Equals', '3'),
('VictoryDominationSetting', 'Game', 'BBGVictorySpeedSlider', 'Equals', '3'),
('VictoryConquestSetting', 'Game', 'BBGVictorySpeedSlider', 'Equals', '3'),
('VictoryReligiousSetting', 'Game', 'BBGVictorySpeedSlider', 'Equals', '3'),
('VictoryMasterSlider', 'Game', 'RULESET', 'Equals', 'RULESET_EXPANSION_2'),
('VictoryCulturalSetting', 'Game', 'RULESET', 'Equals', 'RULESET_EXPANSION_2'),
('VictoryScoreSetting', 'Game', 'RULESET', 'Equals', 'RULESET_EXPANSION_2'),
('VictoryScienceSetting', 'Game', 'RULESET', 'Equals', 'RULESET_EXPANSION_2'),
('VictoryDiploSetting', 'Game', 'RULESET', 'Equals', 'RULESET_EXPANSION_2'),
('VictoryDominationSetting', 'Game', 'RULESET', 'Equals', 'RULESET_EXPANSION_2'),
('VictoryConquestSetting', 'Game', 'RULESET', 'Equals', 'RULESET_EXPANSION_2'),
('VictoryReligiousSetting', 'Game', 'RULESET', 'Equals', 'RULESET_EXPANSION_2'),
('VICTORY_CULTURE', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '3'),
('VICTORY_TRADITIONAL_DOMINATION', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '3'),
('VICTORY_CONQUEST', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '3'),
('VICTORY_RELIGIOUS', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '3'),
('VICTORY_TECHNOLOGY', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '3'),
('VICTORY_DIPLOMATIC', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '3'),
('VICTORY_SCORE', 'Game', 'BBGVictorySpeedSlider', 'NotEquals', '3'),
('TurnLimit', 'Game', 'BBGVictoryScoreSettingDomain', 'NotEquals', '1'),
('TurnLimit', 'Game', 'BBGVictoryScoreSettingDomain', 'NotEquals', '2');

INSERT OR REPLACE INTO DomainValues (Domain, Value, Name, Description, SortIndex) VALUES
('BBCCSetting', '-1', 'LOC_BBG_FRONT_BBCC_SETTING_M1_NAME', 'LOC_BBG_FRONT_BBCC_SETTING_M1_DESC', '10'),
('BBCCSetting', '0', 'LOC_BBG_FRONT_BBCC_SETTING_0_NAME', 'LOC_BBG_FRONT_BBCC_SETTING_0_DESC', '20'),
('BBCCSetting', '1', 'LOC_BBG_FRONT_BBCC_SETTING_1_NAME', 'LOC_BBG_FRONT_BBCC_SETTING_1_DESC', '30'),
('BBCCSettingYield', '0', 'LOC_BBG_FRONT_BBCC_SETTING_YIELD_0_NAME', 'LOC_BBG_FRONT_BBCC_SETTING_YIELD_0_DESC', '10'),
('BBCCSettingYield', '1', 'LOC_BBG_FRONT_BBCC_SETTING_YIELD_1_NAME', 'LOC_BBG_FRONT_BBCC_SETTING_YIELD_1_DESC', '20'),
('BBCCSettingYield', '2', 'LOC_BBG_FRONT_BBCC_SETTING_YIELD_2_NAME', 'LOC_BBG_FRONT_BBCC_SETTING_YIELD_2_DESC', '30'),
('SettlersConfig', '-1', 'LOC_BBG_SETTLER_CONFIG_BASEGAME_NAME', 'LOC_BBG_SETTLER_CONFIG_BASEGAME_DESC', '10'),
('SettlersConfig', '0', 'LOC_BBG_SETTLER_CONFIG_CHILL_NAME', 'LOC_BBG_SETTLER_CONFIG_CHILL_DESC', '20'),
('BBGBarbsSetting', '0', 'BBG_FRONT_BARB_SETTING_0_NAME', 'BBG_FRONT_BARB_SETTING_0_DESC', '10'),
('BBGBarbsSetting', '3', 'BBG_FRONT_BARB_SETTING_3_NAME', 'BBG_FRONT_BARB_SETTING_3_DESC', '20'),
('BBGBarbsSetting', '1', 'BBG_FRONT_BARB_SETTING_1_NAME', 'BBG_FRONT_BARB_SETTING_1_DESC', '30'),
('BBGBarbsSetting', '2', 'BBG_FRONT_BARB_SETTING_2_NAME', 'BBG_FRONT_BARB_SETTING_2_DESC', '40'),
('BBGBarbsSetting', '-1', 'BBG_FRONT_BARB_SETTING_OFF_NAME', 'BBG_FRONT_BARB_SETTING_OFF_DESC', '50'),
('BBGVictorySpeedSliderRange', '0', 'BBG_FRONT_MASTER_SETTING_0_NAME', 'BBG_FRONT_MASTER_SETTING_0_DESC', '10'),
('BBGVictorySpeedSliderRange', '1', 'BBG_FRONT_MASTER_SETTING_1_NAME', 'BBG_FRONT_MASTER_SETTING_1_DESC', '20'),
('BBGVictorySpeedSliderRange', '2', 'BBG_FRONT_MASTER_SETTING_2_NAME', 'BBG_FRONT_MASTER_SETTING_2_DESC', '30'),
('BBGVictorySpeedSliderRange', '3', 'BBG_FRONT_MASTER_SETTING_CUSTOM_NAME', 'BBG_FRONT_MASTER_SETTING_CUSTOM_DESC', '50'),
('BBGVictorySpeedSliderRange', '5', 'BBG_FRONT_MASTER_SETTING_BBG_LEGACY_NAME', 'BBG_FRONT_MASTER_SETTING_BBG_LEGACY_DESC', '50'),
('BBGVictorySpeedSliderRange', '-1', 'BBG_FRONT_MASTER_SETTING_OFF_NAME', 'BBG_FRONT_MASTER_SETTING_OFF_DESC', '40'),
('BBGVictoryCulturalSettingDomain', '0', 'BBG_FRONT_VICTORY_CULTURAL_SETTING_0_NAME', 'BBG_FRONT_VICTORY_CULTURAL_SETTING_0_DESC', '10'),
('BBGVictoryCulturalSettingDomain', '1', 'BBG_FRONT_VICTORY_CULTURAL_SETTING_1_NAME', 'BBG_FRONT_VICTORY_CULTURAL_SETTING_1_DESC', '20'),
('BBGVictoryCulturalSettingDomain', '2', 'BBG_FRONT_VICTORY_CULTURAL_SETTING_2_NAME', 'BBG_FRONT_VICTORY_CULTURAL_SETTING_2_DESC', '30'),
('BBGVictoryCulturalSettingDomain', '3', 'BBG_FRONT_VICTORY_CULTURAL_SETTING_3_NAME', 'BBG_FRONT_VICTORY_CULTURAL_SETTING_3_DESC', '40'),
('BBGVictoryScoreSettingDomain', '0', 'BBG_FRONT_VICTORY_SCORE_SETTING_0_NAME', 'BBG_FRONT_VICTORY_SCORE_SETTING_0_DESC', '10'),
('BBGVictoryScoreSettingDomain', '1', 'BBG_FRONT_VICTORY_SCORE_SETTING_1_NAME', 'BBG_FRONT_VICTORY_SCORE_SETTING_1_DESC', '20'),
('BBGVictoryScoreSettingDomain', '2', 'BBG_FRONT_VICTORY_SCORE_SETTING_2_NAME', 'BBG_FRONT_VICTORY_SCORE_SETTING_2_DESC', '30'),
('BBGVictoryScoreSettingDomain', '3', 'BBG_FRONT_VICTORY_SCORE_SETTING_3_NAME', 'BBG_FRONT_VICTORY_SCORE_SETTING_3_DESC', '40'),
('BBGVictoryScienceSettingDomain', '0', 'BBG_FRONT_VICTORY_SCIENCE_SETTING_0_NAME', 'BBG_FRONT_VICTORY_SCIENCE_SETTING_0_DESC', '10'),
('BBGVictoryScienceSettingDomain', '1', 'BBG_FRONT_VICTORY_SCIENCE_SETTING_1_NAME', 'BBG_FRONT_VICTORY_SCIENCE_SETTING_1_DESC', '20'),
('BBGVictoryScienceSettingDomain', '2', 'BBG_FRONT_VICTORY_SCIENCE_SETTING_2_NAME', 'BBG_FRONT_VICTORY_SCIENCE_SETTING_2_DESC', '30'),
('BBGVictoryScienceSettingDomain', '3', 'BBG_FRONT_VICTORY_SCIENCE_SETTING_3_NAME', 'BBG_FRONT_VICTORY_SCIENCE_SETTING_3_DESC', '40'),
('BBGVictoryDiploSettingDomain', '0', 'BBG_FRONT_VICTORY_DIPLO_SETTING_0_NAME', 'BBG_FRONT_VICTORY_DIPLO_SETTING_0_DESC', '10'),
('BBGVictoryDiploSettingDomain', '1', 'BBG_FRONT_VICTORY_DIPLO_SETTING_1_NAME', 'BBG_FRONT_VICTORY_DIPLO_SETTING_1_DESC', '20'),
('BBGVictoryDiploSettingDomain', '2', 'BBG_FRONT_VICTORY_DIPLO_SETTING_2_NAME', 'BBG_FRONT_VICTORY_DIPLO_SETTING_2_DESC', '30'),
('BBGVictoryDiploSettingDomain', '3', 'BBG_FRONT_VICTORY_DIPLO_SETTING_3_NAME', 'BBG_FRONT_VICTORY_DIPLO_SETTING_3_DESC', '40'),
('BBGVictoryReligiousSettingDomain', '0', 'BBG_FRONT_VICTORY_RELIGIOUS_SETTING_0_NAME', 'BBG_FRONT_VICTORY_RELIGIOUS_SETTING_0_DESC', '10'),
('BBGVictoryReligiousSettingDomain', '1', 'BBG_FRONT_VICTORY_RELIGIOUS_SETTING_1_NAME', 'BBG_FRONT_VICTORY_RELIGIOUS_SETTING_1_DESC', '20'),
('BBGVictoryReligiousSettingDomain', '2', 'BBG_FRONT_VICTORY_RELIGIOUS_SETTING_2_NAME', 'BBG_FRONT_VICTORY_RELIGIOUS_SETTING_2_DESC', '30'),
('BBGVictoryReligiousSettingDomain', '3', 'BBG_FRONT_VICTORY_RELIGIOUS_SETTING_3_NAME', 'BBG_FRONT_VICTORY_RELIGIOUS_SETTING_3_DESC', '40'),
('BBGVictoryDominationSettingDomain', '0', 'BBG_FRONT_VICTORY_DOMINATION_SETTING_0_NAME', 'BBG_FRONT_VICTORY_DOMINATION_SETTING_0_DESC', '10'),
('BBGVictoryDominationSettingDomain', '1', 'BBG_FRONT_VICTORY_DOMINATION_SETTING_1_NAME', 'BBG_FRONT_VICTORY_DOMINATION_SETTING_1_DESC', '20'),
('BBGVictoryDominationSettingDomain', '2', 'BBG_FRONT_VICTORY_DOMINATION_SETTING_2_NAME', 'BBG_FRONT_VICTORY_DOMINATION_SETTING_2_DESC', '30'),
('BBGVictoryDominationSettingDomain', '3', 'BBG_FRONT_VICTORY_DOMINATION_SETTING_3_NAME', 'BBG_FRONT_VICTORY_DOMINATION_SETTING_3_DESC', '40'),
('BBGVictoryConquestSettingDomain', '0', 'BBG_FRONT_VICTORY_CONQUEST_SETTING_0_NAME', 'BBG_FRONT_VICTORY_CONQUEST_SETTING_0_DESC', '10'),
('BBGVictoryConquestSettingDomain', '3', 'BBG_FRONT_VICTORY_CONQUEST_SETTING_3_NAME', 'BBG_FRONT_VICTORY_CONQUEST_SETTING_3_DESC', '40');

INSERT OR REPLACE INTO ConfigurationUpdates (SourceGroup, SourceId, SourceValue, TargetGroup, TargetId, TargetValue, Hash, Static) VALUES
('Game', 'BARBS_SETTING', '0', 'Game', 'GAME_NO_BARBARIANS', '0', DEFAULT, DEFAULT),
('Game', 'BARBS_SETTING', '1', 'Game', 'GAME_NO_BARBARIANS', '1', DEFAULT, DEFAULT),
('Game', 'BARBS_SETTING', '2', 'Game', 'GAME_NO_BARBARIANS', '1', DEFAULT, DEFAULT),
('Game', 'BARBS_SETTING', '3', 'Game', 'GAME_NO_BARBARIANS', '1', DEFAULT, DEFAULT),
('Game', 'BARBS_SETTING', '-1', 'Game', 'GAME_NO_BARBARIANS', '1', DEFAULT, DEFAULT),
('Game', 'VictoryCulturalSetting', '0', 'Game', 'VICTORY_CULTURE', '1', DEFAULT, DEFAULT),
('Game', 'VictoryCulturalSetting', '1', 'Game', 'VICTORY_CULTURE', '1', DEFAULT, DEFAULT),
('Game', 'VictoryCulturalSetting', '2', 'Game', 'VICTORY_CULTURE', '1', DEFAULT, DEFAULT),
('Game', 'VictoryCulturalSetting', '3', 'Game', 'VICTORY_CULTURE', '0', DEFAULT, DEFAULT),
('Game', 'VictoryScoreSetting', '0', 'Game', 'VICTORY_SCORE', '1', DEFAULT, DEFAULT),
('Game', 'VictoryScoreSetting', '1', 'Game', 'VICTORY_SCORE', '1', DEFAULT, DEFAULT),
('Game', 'VictoryScoreSetting', '2', 'Game', 'VICTORY_SCORE', '1', DEFAULT, DEFAULT),
('Game', 'VictoryScoreSetting', '3', 'Game', 'VICTORY_SCORE', '0', DEFAULT, DEFAULT),
('Game', 'VictoryScoreSetting', '0', 'Game', 'GAME_TURN_LIMIT', 'TURNLIMIT_GAMESPEED', '1', DEFAULT),
('Game', 'VictoryScoreSetting', '1', 'Game', 'GAME_TURN_LIMIT', 'TURNLIMIT_CUSTOM', '1', '1'),
('Game', 'VictoryScoreSetting', '2', 'Game', 'GAME_TURN_LIMIT', 'TURNLIMIT_CUSTOM', '1', '1'),
('Game', 'VictoryScoreSetting', '1', 'Game', 'GAME_MAX_TURNS', '175', DEFAULT, '1'),
('Game', 'VictoryScoreSetting', '2', 'Game', 'GAME_MAX_TURNS', '150', DEFAULT, '1'),
('Game', 'VictoryScoreSetting', '3', 'Game', 'GAME_TURN_LIMIT', 'TURNLIMIT_NONE', '1', DEFAULT),
('Game', 'VictoryScienceSetting', '0', 'Game', 'VICTORY_TECHNOLOGY', '1', DEFAULT, DEFAULT),
('Game', 'VictoryScienceSetting', '1', 'Game', 'VICTORY_TECHNOLOGY', '1', DEFAULT, DEFAULT),
('Game', 'VictoryScienceSetting', '2', 'Game', 'VICTORY_TECHNOLOGY', '1', DEFAULT, DEFAULT),
('Game', 'VictoryScienceSetting', '3', 'Game', 'VICTORY_TECHNOLOGY', '0', DEFAULT, DEFAULT),
('Game', 'VictoryDiploSetting', '0', 'Game', 'VICTORY_DIPLOMATIC', '1', DEFAULT, DEFAULT),
('Game', 'VictoryDiploSetting', '1', 'Game', 'VICTORY_DIPLOMATIC', '1', DEFAULT, DEFAULT),
('Game', 'VictoryDiploSetting', '2', 'Game', 'VICTORY_DIPLOMATIC', '1', DEFAULT, DEFAULT),
('Game', 'VictoryDiploSetting', '3', 'Game', 'VICTORY_DIPLOMATIC', '0', DEFAULT, DEFAULT),
('Game', 'VictoryReligiousSetting', '0', 'Game', 'VICTORY_RELIGIOUS', '1', DEFAULT, DEFAULT),
('Game', 'VictoryReligiousSetting', '1', 'Game', 'VICTORY_RELIGIOUS', '1', DEFAULT, DEFAULT),
('Game', 'VictoryReligiousSetting', '2', 'Game', 'VICTORY_RELIGIOUS', '1', DEFAULT, DEFAULT),
('Game', 'VictoryReligiousSetting', '3', 'Game', 'VICTORY_RELIGIOUS', '0', DEFAULT, DEFAULT),
('Game', 'VictoryConquestSetting', '0', 'Game', 'VICTORY_CONQUEST', '1', DEFAULT, DEFAULT),
('Game', 'VictoryConquestSetting', '3', 'Game', 'VICTORY_CONQUEST', '0', DEFAULT, DEFAULT),
('Game', 'VictoryDominationSetting', '0', 'Game', 'VICTORY_TRADITIONAL_DOMINATION', '1', DEFAULT, DEFAULT),
('Game', 'VictoryDominationSetting', '1', 'Game', 'VICTORY_TRADITIONAL_DOMINATION', '1', DEFAULT, DEFAULT),
('Game', 'VictoryDominationSetting', '2', 'Game', 'VICTORY_TRADITIONAL_DOMINATION', '1', DEFAULT, DEFAULT),
('Game', 'VictoryDominationSetting', '3', 'Game', 'VICTORY_TRADITIONAL_DOMINATION', '0', DEFAULT, DEFAULT),
('Game', 'VictoryDominationSetting', '0', 'Game', 'TRADITIONAL_DOMINATION_LEVEL', '66', DEFAULT, DEFAULT),
('Game', 'VictoryDominationSetting', '1', 'Game', 'TRADITIONAL_DOMINATION_LEVEL', '60', DEFAULT, DEFAULT),
('Game', 'VictoryDominationSetting', '2', 'Game', 'TRADITIONAL_DOMINATION_LEVEL', '50', DEFAULT, DEFAULT),
('Game', 'VictoryDominationSetting', '3', 'Game', 'TRADITIONAL_DOMINATION_LEVEL', '100', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '0', 'Game', 'VictoryDominationSetting', '0', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '0', 'Game', 'VictoryReligiousSetting', '0', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '0', 'Game', 'VictoryDiploSetting', '0', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '0', 'Game', 'VictoryScienceSetting', '0', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '0', 'Game', 'VictoryScoreSetting', '0', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '0', 'Game', 'VictoryConquestSetting', '0', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '0', 'Game', 'VictoryCulturalSetting', '0', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '1', 'Game', 'VictoryDominationSetting', '1', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '1', 'Game', 'VictoryReligiousSetting', '1', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '1', 'Game', 'VictoryDiploSetting', '1', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '1', 'Game', 'VictoryScienceSetting', '1', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '1', 'Game', 'VictoryScoreSetting', '1', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '1', 'Game', 'VictoryCulturalSetting', '1', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '2', 'Game', 'VictoryDominationSetting', '2', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '2', 'Game', 'VictoryReligiousSetting', '2', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '2', 'Game', 'VictoryDiploSetting', '2', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '2', 'Game', 'VictoryScienceSetting', '2', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '2', 'Game', 'VictoryScoreSetting', '2', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '2', 'Game', 'VictoryCulturalSetting', '2', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '5', 'Game', 'VictoryDominationSetting', '3', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '5', 'Game', 'VictoryReligiousSetting', '0', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '5', 'Game', 'VictoryDiploSetting', '2', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '5', 'Game', 'VictoryScienceSetting', '0', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '5', 'Game', 'VictoryScoreSetting', '0', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '5', 'Game', 'VictoryConquestSetting', '0', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '5', 'Game', 'VictoryCulturalSetting', '2', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '-1', 'Game', 'VictoryDominationSetting', '3', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '-1', 'Game', 'VictoryReligiousSetting', '3', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '-1', 'Game', 'VictoryDiploSetting', '3', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '-1', 'Game', 'VictoryScienceSetting', '3', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '-1', 'Game', 'VictoryScoreSetting', '3', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '-1', 'Game', 'VictoryCulturalSetting', '3', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '-1', 'Game', 'VictoryConquestSetting', '3', DEFAULT, DEFAULT),
('Game', 'BBGVictorySpeedSlider', '-1', 'Game', 'GAME_TURN_LIMIT', 'TURNLIMIT_NONE', DEFAULT, '1'),
('Game', 'BBGVictorySpeedSlider', '0', 'Game', 'GAME_MAX_TURNS', '250', DEFAULT, '1'),
('Game', 'BBGVictorySpeedSlider', '1', 'Game', 'GAME_MAX_TURNS', '175', DEFAULT, '1'),
('Game', 'BBGVictorySpeedSlider', '2', 'Game', 'GAME_MAX_TURNS', '150', DEFAULT, '1'),
('Game', 'BBGVictorySpeedSlider', '1', 'Game', 'GAME_TURN_LIMIT', 'TURNLIMIT_CUSTOM', '1', '1'),
('Game', 'BBGVictorySpeedSlider', '2', 'Game', 'GAME_TURN_LIMIT', 'TURNLIMIT_CUSTOM', '1', '1'),
('Game', 'BBGVictorySpeedSlider', '3', 'Game', 'GAME_TURN_LIMIT', 'TURNLIMIT_CUSTOM', '1', '1'),
('Game', 'BBGVictorySpeedSlider', '1', 'Game', 'GAME_SPEED_TYPE', 'GAMESPEED_ONLINE', '1', DEFAULT),
('Game', 'BBGVictorySpeedSlider', '2', 'Game', 'GAME_SPEED_TYPE', 'GAMESPEED_ONLINE', '1', DEFAULT),
('Game', 'BBGVictorySpeedSlider', '3', 'Game', 'GAME_SPEED_TYPE', 'GAMESPEED_ONLINE', '1', DEFAULT);