-- ========================================================================
-- =                            OLYMPIA                                   =
-- ========================================================================

DELETE FROM TraitModifiers WHERE TraitType='TRAIT_LEADER_JFD_CABEIRI_MYSTERIES' AND ModifierId = 'JFD_CABEIRI_MYSTERIES_LEVY_DISCOUNT';


-- -- 30/07/25 Basilikoi grant 1 envoy if city follows Olympia religion
-- INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
--     ('HAVE_BASILIKOI_AND_FOLLOWS_RELIGION_REQSET', 'REQUIREMENTSET_TEST_ALL');
-- INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
--     ('HAVE_BASILIKOI_AND_FOLLOWS_RELIGION_REQSET', 'REQUIRES_CITY_HAS_BASILIKOI'),
--     ('HAVE_BASILIKOI_AND_FOLLOWS_RELIGION_REQSET', 'REQUIRES_CITY_FOLLOWS_RELIGION');
-- INSERT INTO Requirements (RequirementId, RequirementType) VALUES
--     ('REQUIRES_CITY_HAS_BASILIKOI', 'REQUIREMENT_CITY_HAS_BUILDING');
-- INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES
--     ('REQUIRES_CITY_HAS_BASILIKOI', 'BuildingType', 'BUILDING_BASILIKOI_PAIDES');

-- INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
--     ('BBG_BASILIKOI_AWARD_1_ENVOY_GIVER', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER', 'HAVE_BASILIKOI_AND_FOLLOWS_RELIGION_REQSET');
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
--     ('BBG_BASILIKOI_AWARD_1_ENVOY_GIVER', 'ModifierId', 'BBG_BASILIKOI_AWARD_1_ENVOY_MODIFIER');
-- INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
--     ('BBG_BASILIKOI_AWARD_1_ENVOY_MODIFIER', 'MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN');
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
--     ('BBG_BASILIKOI_AWARD_1_ENVOY_MODIFIER', 'Amount', 1);

-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
--     ('TRAIT_LEADER_JFD_CABEIRI_MYSTERIES', 'BBG_BASILIKOI_AWARD_1_ENVOY_GIVER');

-- +1 combat strength for melee(moved) and heavy cav units per city state suzed
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
    ('TRAIT_LEADER_JFD_CABEIRI_MYSTERIES', 'BBG_OLYMPIA_MELEE_HEAVY_CS_PER_SUZ');
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
    ('BBG_OLYMPIA_MELEE_HEAVY_CS_PER_SUZ', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY');
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId)
    SELECT 'BBG_MODIFIER_OLYMPIA_SUZ_' || LeaderType, 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'BBG_PLAYER_ATTACKING_IS_SUZERAIN_OF_' || LeaderType || '_REQUIREMENTS'
    FROM Leaders
    WHERE InheritFrom IN
        ('LEADER_MINOR_CIV_CULTURAL', 'LEADER_MINOR_CIV_INDUSTRIAL', 'LEADER_MINOR_CIV_MILITARISTIC',
        'LEADER_MINOR_CIV_RELIGIOUS', 'LEADER_MINOR_CIV_SCIENTIFIC', 'LEADER_MINOR_CIV_TRADE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_OLYMPIA_MELEE_HEAVY_CS_PER_SUZ', 'AbilityType', 'BBG_OLYMPIA_MELEE_HEAVY_CS_PER_SUZ_ABILITY');
INSERT INTO ModifierArguments(ModifierId, Name, Value)
    SELECT 'BBG_MODIFIER_OLYMPIA_SUZ_' || LeaderType, 'Amount', 1
    FROM Leaders
    WHERE InheritFrom IN
        ('LEADER_MINOR_CIV_CULTURAL', 'LEADER_MINOR_CIV_INDUSTRIAL', 'LEADER_MINOR_CIV_MILITARISTIC',
        'LEADER_MINOR_CIV_RELIGIOUS', 'LEADER_MINOR_CIV_SCIENTIFIC', 'LEADER_MINOR_CIV_TRADE');
INSERT INTO TypeTags (Type, Tag) VALUES
    -- ('BBG_OLYMPIA_MELEE_HEAVY_CS_PER_SUZ_ABILITY', 'CLASS_MELEE'),
    ('BBG_OLYMPIA_MELEE_HEAVY_CS_PER_SUZ_ABILITY', 'CLASS_HEAVY_CAVALRY');
INSERT INTO Types (Type, Kind) VALUES
    ('BBG_OLYMPIA_MELEE_HEAVY_CS_PER_SUZ_ABILITY', 'KIND_ABILITY');
INSERT INTO UnitAbilities (UnitAbilityType, Name, Description, Inactive) VALUES
    ('BBG_OLYMPIA_MELEE_HEAVY_CS_PER_SUZ_ABILITY', 'LOC_BBG_OLYMPIA_MELEE_HEAVY_CS_PER_SUZ_ABILITY_NAME', 'LOC_BBG_OLYMPIA_MELEE_HEAVY_CS_PER_SUZ_ABILITY_DESC', 1);
INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId)
    SELECT 'BBG_OLYMPIA_MELEE_HEAVY_CS_PER_SUZ_ABILITY', 'BBG_MODIFIER_OLYMPIA_SUZ_' || LeaderType
    FROM Leaders
    WHERE InheritFrom IN
        ('LEADER_MINOR_CIV_CULTURAL', 'LEADER_MINOR_CIV_INDUSTRIAL', 'LEADER_MINOR_CIV_MILITARISTIC',
        'LEADER_MINOR_CIV_RELIGIOUS', 'LEADER_MINOR_CIV_SCIENTIFIC', 'LEADER_MINOR_CIV_TRADE');
-- THIS USE THE SAME LOC AS HUNGARY/VARANGIAN CAUSE THIS IS THE SAME KIND OF MODIFIER
INSERT INTO ModifierStrings(ModifierId, Context, Text) 
    SELECT 'BBG_MODIFIER_OLYMPIA_SUZ_' || LeaderType, 'Preview', '+{1_Amount} {LOC_ABILITY_HUSZAIR_COMBAT_PREVIEW} {'||Name||'}'
    FROM Leaders
    WHERE InheritFrom IN
        ('LEADER_MINOR_CIV_CULTURAL', 'LEADER_MINOR_CIV_INDUSTRIAL', 'LEADER_MINOR_CIV_MILITARISTIC',
        'LEADER_MINOR_CIV_RELIGIOUS', 'LEADER_MINOR_CIV_SCIENTIFIC', 'LEADER_MINOR_CIV_TRADE');

-- -- 30/07/25 Basilikoi grant 1 science per population in city following Olympia's religion
-- INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
--     ('BBG_SCIENCE_POP_OLYMPIA', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION', 'HAVE_BASILIKOI_AND_FOLLOWS_RELIGION_REQSET');
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
--     ('BBG_SCIENCE_POP_OLYMPIA', 'Amount', 1),
--     ('BBG_SCIENCE_POP_OLYMPIA', 'YieldType', 'YIELD_SCIENCE');

-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
--     ('TRAIT_LEADER_JFD_CABEIRI_MYSTERIES', 'BBG_SCIENCE_POP_OLYMPIA');


-- Olympia's melee +1 movement with zzzx
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_JFD_CABEIRI_MYSTERIES', 'CCB_OLYMPIA_MELEE_MOVEMENT_BONUS');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_OLYMPIA_MELEE_MOVEMENT_BONUS', 'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER', 0, 0, 0, 'BBG_UTILS_PLAYER_HAS_CIVIC_POLITICAL_PHILOSOPHY_REQSET', NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_OLYMPIA_MELEE_MOVEMENT_BONUS', 'ModifierId', 'CCB_OLYMPIA_MELEE_MOVEMENT_BONUS_MODIFIER');
-- 
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_OLYMPIA_MELEE_MOVEMENT_BONUS_MODIFIER', 'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', 0, 0, 0, 'CCB_REQSET_UNIT_IS_MELEE', NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_OLYMPIA_MELEE_MOVEMENT_BONUS_MODIFIER', 'Amount', '1');
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('CCB_REQSET_UNIT_IS_MELEE', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('CCB_REQSET_UNIT_IS_MELEE', 'CCB_REQ_UNIT_IS_MELEE');
INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('CCB_REQ_UNIT_IS_MELEE', 'REQUIREMENT_UNIT_PROMOTION_CLASS_MATCHES');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('CCB_REQ_UNIT_IS_MELEE', 'UnitPromotionClass', 'PROMOTION_CLASS_MELEE');

-- +1 gold per user envoy
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_JFD_CABEIRI_MYSTERIES', 'CCB_OLYMPIA_GOLD_PER_ENVOY');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_OLYMPIA_GOLD_PER_ENVOY', 'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE_PER_USED_INFLUENCE_TOKEN', 0, 0, 0, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_OLYMPIA_GOLD_PER_ENVOY', 'Amount', '1'), 
('CCB_OLYMPIA_GOLD_PER_ENVOY', 'YieldType', 'YIELD_GOLD');

-- +1 envoy when capture city
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_JFD_CABEIRI_MYSTERIES', 'CCB_OLYMPIA_CAPTURE_CITY_STATE_ENVOY');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
-- ('CCB_OLYMPIA_CAPTURE_CITY_STATE_ENVOY', 'MODIFIER_PLAYER_CAPTURED_CITY_ATTACH_MODIFIER', 0, 0, 0, NULL, 'REQUIREMENTS_OPPONENT_IS_MINOR_CIV');
('CCB_OLYMPIA_CAPTURE_CITY_STATE_ENVOY', 'MODIFIER_PLAYER_CAPTURED_CITY_ATTACH_MODIFIER', 0, 0, 0, NULL, NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_OLYMPIA_CAPTURE_CITY_STATE_ENVOY', 'ModifierId', 'CCB_OLYMPIA_CAPTURE_CITY_STATE_ENVOY_MODIFIER');

-- INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
-- ('CCB_REQSET_OPPONENT_IS_MINOR_CIV', 'REQUIREMENTSET_TEST_ANY');

-- INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
-- ('CCB_REQSET_OPPONENT_IS_MINOR_CIV', 'CCB_LEADER_TAG_IS_MINOR_CIV');

-- INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
-- ('CCB_LEADER_TAG_IS_MINOR_CIV', 'REQUIREMENT_LEADER_TYPE_MATCHES');

-- INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
-- ('CCB_LEADER_TAG_IS_MINOR_CIV', 'LeaderType', 'LEADER_MINOR_CIV_FEZ');

--
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('CCB_OLYMPIA_CAPTURE_CITY_STATE_ENVOY_MODIFIER', 'MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN', 0, 0, 0, NULL, NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('CCB_OLYMPIA_CAPTURE_CITY_STATE_ENVOY_MODIFIER', 'Amount', '2');

-- heavy cavalry +1 combat per leadered city-state

-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
-- ('TRAIT_LEADER_JFD_CABEIRI_MYSTERIES', 'CCB_OLYMPIA_HEAVY_CAVALRY_COMBAT_BONUS_SUK_FEZ');

-- INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
-- ('CCB_OLYMPIA_HEAVY_CAVALRY_COMBAT_BONUS_SUK_FEZ', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH', 0, 0, 0, 'BBG_PLAYER_IS_SUZERAIN_OF_LEADER_MINOR_CIV_FEZ_REQUIREMENTS', 'CCB_REQSET_OLYMPIA_UNIT_IS_HEAVY_CAVALRY');

-- INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
-- ('CCB_OLYMPIA_HEAVY_CAVALRY_COMBAT_BONUS_SUK_FEZ', 'Amount', '1');

-- INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
-- ('BBG_PLAYER_IS_SUZERAIN_OF_LEADER_MINOR_CIV_FEZ_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'), 
-- ('CCB_REQSET_OLYMPIA_UNIT_IS_HEAVY_CAVALRY', 'REQUIREMENTSET_TEST_ALL');

-- INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
-- ('CCB_REQSET_OLYMPIA_UNIT_IS_HEAVY_CAVALRY', 'UNIT_IS_HEAVY_CAVALRY');

