-- 阿拉伯
-- !Civilization
-- Arabia gets +1 Great Prophet point per turn after researching astrology
INSERT OR IGNORE INTO Modifiers (ModifierId , ModifierType, SubjectRequirementSetId)
    VALUES ('TRAIT_BONUS_GREAT_PROPHET_POINT_CPLMOD' , 'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS' , 'PLAYER_HAS_ASTROLOGY_REQUIREMENTS_CPLMOD');
INSERT OR IGNORE INTO ModifierArguments (ModifierId , Name , Value)
    VALUES ('TRAIT_BONUS_GREAT_PROPHET_POINT_CPLMOD' , 'GreatPersonClassType' , 'GREAT_PERSON_CLASS_PROPHET');
INSERT OR IGNORE INTO ModifierArguments (ModifierId , Name , Value)
    VALUES ('TRAIT_BONUS_GREAT_PROPHET_POINT_CPLMOD' , 'Amount' , '1');
--UPDATE TraitModifiers SET ModifierId='TRAIT_BONUS_GREAT_PROPHET_POINT_CPLMOD' WHERE ModifierId='TRAIT_GUARANTEE_ONE_PROPHET';
INSERT OR IGNORE INTO TraitModifiers (TraitType, ModifierId) VALUES ('TRAIT_CIVILIZATION_LAST_PROPHET', 'TRAIT_BONUS_GREAT_PROPHET_POINT_CPLMOD');
INSERT OR IGNORE INTO RequirementSets (RequirementSetId , RequirementSetType)
	VALUES ('PLAYER_HAS_ASTROLOGY_REQUIREMENTS_CPLMOD' , 'REQUIREMENTSET_TEST_ALL');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId , RequirementId)
	VALUES ('PLAYER_HAS_ASTROLOGY_REQUIREMENTS_CPLMOD' , 'REQUIRES_PLAYER_HAS_ASTROLOGY_CPLMOD');
INSERT OR IGNORE INTO Requirements (RequirementId , RequirementType)
	VALUES ('REQUIRES_PLAYER_HAS_ASTROLOGY_CPLMOD' , 'REQUIREMENT_PLAYER_HAS_TECHNOLOGY');
INSERT OR IGNORE INTO RequirementArguments (RequirementId , Name , Value)
	VALUES ('REQUIRES_PLAYER_HAS_ASTROLOGY_CPLMOD' , 'TechnologyType' , 'TECH_ASTROLOGY');

-- Campus and Holy Site +1 if adjacant to each other
INSERT INTO Adjacency_YieldChanges(ID, Description, YieldType, YieldChange, AdjacentDistrict) VALUES
    ('BBG_Campus_Arabia_HS', 'BBG_LOC_CAMPUS_ARABIA_HS', 'YIELD_SCIENCE', 1, 'DISTRICT_HOLY_SITE'),
    ('BBG_HS_Arabia_Campus', 'BBG_LOC_HS_ARABIA_CAMPUS', 'YIELD_FAITH', 1, 'DISTRICT_CAMPUS');
INSERT INTO District_Adjacencies(DistrictType, YieldChangeId) VALUES
    ('DISTRICT_CAMPUS', 'BBG_Campus_Arabia_HS'),
    ('DISTRICT_HOLY_SITE', 'BBG_HS_Arabia_Campus');
INSERT INTO ExcludedAdjacencies(TraitType, YieldChangeId)
    SELECT TraitType, 'BBG_Campus_Arabia_HS' FROM CivilizationTraits WHERE CivilizationType != 'CIVILIZATION_ARABIA' GROUP BY CivilizationType;
INSERT INTO ExcludedAdjacencies(TraitType, YieldChangeId)
    SELECT TraitType, 'BBG_HS_Arabia_Campus' FROM CivilizationTraits WHERE CivilizationType != 'CIVILIZATION_ARABIA' GROUP BY CivilizationType;

-- !Saladin
-- Arabia's Worship Building Bonus increased from 10% to 20%
-- 26/02/25 reduced to 10% base, 20% at reformed church

INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) VALUES
    ('BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_CULTURE', 'MODIFIER_PLAYER_ADD_RELIGIOUS_BUILDING_MULTIPLIER', 'BBG_UTILS_PLAYER_HAS_CIVIC_REFORMED_CHURCH_REQSET'),
    ('BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_FAITH', 'MODIFIER_PLAYER_ADD_RELIGIOUS_BUILDING_MULTIPLIER', 'BBG_UTILS_PLAYER_HAS_CIVIC_REFORMED_CHURCH_REQSET'),
    ('BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_SCIENCE', 'MODIFIER_PLAYER_ADD_RELIGIOUS_BUILDING_MULTIPLIER', 'BBG_UTILS_PLAYER_HAS_CIVIC_REFORMED_CHURCH_REQSET');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_CULTURE', 'YieldType', 'YIELD_CULTURE'),
    ('BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_CULTURE', 'Multiplier', 10),
    ('BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_CULTURE', 'Founder', 1),
    ('BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_FAITH', 'YieldType', 'YIELD_FAITH'),
    ('BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_FAITH', 'Multiplier', 10),
    ('BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_FAITH', 'Founder', 1),
    ('BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
    ('BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_SCIENCE', 'Multiplier', 10),
    ('BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_SCIENCE', 'Founder', 1);

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
    ('TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH', 'BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_CULTURE'),
    ('TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH', 'BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_FAITH'),
    ('TRAIT_LEADER_RIGHTEOUSNESS_OF_FAITH', 'BBG_ARABIA_MULTIPLIER_REFORMED_CHURCH_SCIENCE');

-- !Saladin-Sultan
-- 05/03/2024 -1 units maintenance cost
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
     ('BBG_SULTAN_UNITMAINTENANCEDISCOUNT', 'MODIFIER_PLAYER_ADJUST_UNIT_MAINTENANCE_DISCOUNT');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
     ('BBG_SULTAN_UNITMAINTENANCEDISCOUNT', 'Amount', '1');
 INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
     ('TRAIT_LEADER_SALADIN_ALT', 'BBG_SULTAN_UNITMAINTENANCEDISCOUNT');


-- 28/03/25 Rework Units get +5 combat strength if they are within 1 tile of an apostle.
-- Can buy encampment and campus buildings with faith at a 10% discount 
-- (delete old flanking/support ability)
DELETE FROM TraitModifiers WHERE TraitType='TRAIT_LEADER_SALADIN_ALT' AND ModifierId='SALADIN_ALT_FLANKING_ABILITY';

-- Can buy encampment and campus buildings
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
     ('BBG_SULTAN_JESUIT_ENCAMPMENT', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE'),
     ('BBG_SULTAN_JESUIT_CAMPUS', 'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
     ('BBG_SULTAN_JESUIT_ENCAMPMENT', 'DistrictType', 'DISTRICT_ENCAMPMENT'),
     ('BBG_SULTAN_JESUIT_CAMPUS', 'DistrictType', 'DISTRICT_CAMPUS');
 INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
     ('TRAIT_LEADER_SALADIN_ALT', 'BBG_SULTAN_JESUIT_ENCAMPMENT'),
     ('TRAIT_LEADER_SALADIN_ALT', 'BBG_SULTAN_JESUIT_CAMPUS');

--  with faith at a 10% discount
INSERT INTO Modifiers (ModifierId, ModifierType)
     SELECT 'BBG_SULTAN_CHEAPER_PURCHASE_' || b.BuildingType, 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PURCHASE_COST' 
    FROM Buildings b LEFT JOIN BuildingReplaces br ON b.BuildingType = br.CivUniqueBuildingType WHERE b.PrereqDistrict IN ('DISTRICT_CAMPUS', 'DISTRICT_ENCAMPMENT') AND br.CivUniqueBuildingType IS NULL;
INSERT INTO ModifierArguments(ModifierId, Name, Value)
    SELECT 'BBG_SULTAN_CHEAPER_PURCHASE_' || b.BuildingType, 'BuildingType', b.BuildingType 
    FROM Buildings b LEFT JOIN BuildingReplaces br ON b.BuildingType = br.CivUniqueBuildingType WHERE b.PrereqDistrict IN ('DISTRICT_CAMPUS', 'DISTRICT_ENCAMPMENT') AND br.CivUniqueBuildingType IS NULL;
INSERT INTO ModifierArguments(ModifierId, Name, Value)
    SELECT 'BBG_SULTAN_CHEAPER_PURCHASE_' || b.BuildingType, 'Amount', 10 
    FROM Buildings b LEFT JOIN BuildingReplaces br ON b.BuildingType = br.CivUniqueBuildingType WHERE b.PrereqDistrict IN ('DISTRICT_CAMPUS', 'DISTRICT_ENCAMPMENT') AND br.CivUniqueBuildingType IS NULL;
INSERT INTO TraitModifiers (TraitType, ModifierId)
    SELECT 'TRAIT_LEADER_SALADIN_ALT', 'BBG_SULTAN_CHEAPER_PURCHASE_' || b.BuildingType 
    FROM Buildings b LEFT JOIN BuildingReplaces br ON b.BuildingType = br.CivUniqueBuildingType WHERE b.PrereqDistrict IN ('DISTRICT_CAMPUS', 'DISTRICT_ENCAMPMENT') AND br.CivUniqueBuildingType IS NULL;


-- Units get +5 combat strength if they are within 1 tile of an apostle.
INSERT INTO Requirements (RequirementId, RequirementType) VALUES
     ('BBG_ADJACENT_FRIENDLY_UNIT_IS_APOSTLE_REQUIREMENT', 'REQUIREMENT_PLOT_ADJACENT_FRIENDLY_UNIT_TYPE_MATCHES');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES
     ('BBG_ADJACENT_FRIENDLY_UNIT_IS_APOSTLE_REQUIREMENT', 'UnitType', 'UNIT_APOSTLE');
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
     ('BBG_ADJACENT_FRIENDLY_UNIT_IS_APOSTLE_REQSET', 'REQUIREMENTSET_TEST_ANY');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
     ('BBG_ADJACENT_FRIENDLY_UNIT_IS_APOSTLE_REQSET', 'BBG_ADJACENT_FRIENDLY_UNIT_IS_APOSTLE_REQUIREMENT'),
     ('BBG_ADJACENT_FRIENDLY_UNIT_IS_APOSTLE_REQSET', 'PLOT_UNIT_IS_APOSTLE_REQUIREMENTS');


INSERT INTO Types (Type, Kind) VALUES
    ('BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_ABILITY', 'KIND_ABILITY');
INSERT INTO TypeTags (Type, Tag) VALUES
    ('BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_ABILITY', 'CLASS_ALL_COMBAT_UNITS');


INSERT INTO UnitAbilities (UnitAbilityType, Name, Description, Inactive) VALUES
    ('BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_ABILITY', 'LOC_BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_ABILITY_NAME', 'LOC_BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_ABILITY_DESC', 1);
INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES
    ('BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_ABILITY', 'BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_MODIFIER');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_GIVER', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 'BBG_ADJACENT_FRIENDLY_UNIT_IS_APOSTLE_REQSET'),
    ('BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_MODIFIER', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_GIVER', 'AbilityType', 'BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_ABILITY'),    
    ('BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_MODIFIER', 'Amount', 5);
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
    ('TRAIT_LEADER_SALADIN_ALT', 'BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_GIVER');
INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
    ('BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_MODIFIER', 'Preview', 'LOC_BBG_SULTAN_COMBAT_ADJACENT_APOSTLE_ABILITY_DESC');